title: Contributor
author: Cisco Talos
email: https://github.com/recvfrom/contributor/issues
description: > 
  The Contributor project aims to help people gain experience analyzing
  real-world malware and contribute valuable detection content to defend 
  the millions of Snort and ClamAV users worldwide.  Join us in the fight
  against malware!

header_pages:
 - getting-started.md
 - knowledge-base.md
 - hall-of-fame.md
 - about.md

theme: minima
